name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - cartopy
  - geopandas
  - plotly
  - seaborn
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
